package planet.heavenlybody;

import java.util.HashSet;
import java.util.Set;


public class HeavenlyBody {
    private final String name;
    private final double orbitalPeriod;
    //    using hash sets
    private final Set<HeavenlyBody> satellites;
    private final BodyType bodyType;

    enum BodyType {
        STAR, PLANET, MOON, ASTEROID, DEFAULT
    }

    public HeavenlyBody(String name, double orbitalPeriod) {
        this(name, orbitalPeriod, BodyType.DEFAULT);
    }

    public HeavenlyBody(String name, double orbitalPeriod, BodyType bodyType) {
        this.name = name;
        this.orbitalPeriod = orbitalPeriod;
        satellites = new HashSet<>();
        this.bodyType = bodyType;
    }

    public BodyType getBodyType() {
        return bodyType;
    }

    public String getName() {
        return name;
    }

    public double getOrbitalPeriod() {
        return orbitalPeriod;
    }

    public boolean addSattelite(HeavenlyBody sattelite) {

        return this.satellites.add(sattelite);

    }

    public Set<HeavenlyBody> getSatellites() {
        return new HashSet<>(this.satellites);
    }

    //    Ovveriding Hash method to check equality of an object
    @Override
    public final boolean equals(Object obj) {
//        if this object and passed object are equal, that mean is the sam object so no more checking is necessary
        if (this == obj) {
            return true;
        }

        if (obj instanceof HeavenlyBody) {
            HeavenlyBody body = (HeavenlyBody) obj;
            if (this.name.equals(body.getName())) {
                return this.bodyType == body.getBodyType();
            }
        }
        return false;

    }

    //    check if class are equal, the same class should always generate the same hashCode
    @Override
    public final int hashCode() {
//        using some number (any number 57 in this case) and adding to hash generated by String class
//        this way we know that hash will always be the same for the same object
        return this.name.hashCode() + 57 + bodyType.hashCode();
    }
}
