package planet.heavenlybody;

import java.util.HashSet;
import java.util.Set;

public final class HeavenlyBody {
    private final String name;
    private final double orbitalPeriod;
    //    using hash sets
    private final Set<HeavenlyBody> satellites;

    public HeavenlyBody(String name, double orbitalPeriod) {
        this.name = name;
        this.orbitalPeriod = orbitalPeriod;
        satellites = new HashSet<>();
    }

    public String getName() {
        return name;
    }

    public double getOrbitalPeriod() {
        return orbitalPeriod;
    }

    public boolean addMoon(HeavenlyBody moon) {
        return this.satellites.add(moon);
    }

    public Set<HeavenlyBody> getSatellites() {
        return new HashSet<>(this.satellites);
    }

    //    Ovveriding Hash method to check equality of an object
    @Override
    public boolean equals(Object obj) {
//        if this object and passed object are equal, that mean is the sam object so no more checking is necessary
        if (this == obj) {
            return true;
        }
//         check if obj is null and then check if they are the same class (in case of subclasses)
        if ((obj == null) || (obj.getClass() != this.getClass())) {
            return false;
        }
        String objName = ((HeavenlyBody) obj).getName();
        return this.name.equals(objName);
    }

//    check if class are equal, the same class should always generate the same hashCode
    @Override
    public int hashCode() {
//        using some number (any number 57 in this case) and adding to hash generated by String class
//        this way we know that hash will always be the same for the same object
        return this.name.hashCode() + 57;
    }
}
